name = "templ-counter"
main = "./build/worker.mjs"
compatibility_date = "2022-05-13"
compatibility_flags = [
    "streams_enable_constructors"
]

[[kv_namespaces]]
binding = "templ_counter"
id = "fb79b1588eb546ba95643b0baf210487"

[build]
command = "make build"
